name: Test Connection

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'SSH command to run on remote server'
        required: false
        default: 'whoami && hostname && uptime'
        type: string

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSL_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      
    - name: Test SSH connection
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
          -o ConnectTimeout=10 \
          ${{secrets.REMOTE_USER}}@${{ secrets.REMOTE_HOST }} \
          "${{ github.event.inputs.command || 'whoami && hostname && uptime' }}"
          
    - name: Securely remove SSH key
      if: always()
      run: |
        if [ -f ~/.ssh/id_rsa ]; then
            echo "Overwriting private key with random data prior to deleting"
            # Overwrite with random data of the same size
            filesize=$(stat -c%s ~/.ssh/id_rsa)
            head -c $filesize /dev/urandom > ~/.ssh/id_rsa.overwrite
            mv ~/.ssh/id_rsa.overwrite ~/.ssh/id_rsa
            # Now delete
            echo "Deleting private key"
            rm -f ~/.ssh/id_rsa
            echo "SSH key securely overwritten and deleted"
        fi